### ISSUE TITLE
ietf-yang-library-revisions

### ISSUE THREAD

**Issue by bclaise** [JeanQuilbeufHuawei/draft-collected-data-manifest#13]
https://datatracker.ietf.org/doc/html/draft-ietf-netmod-yang-module-versioning-05 contains ietf-yang-library-revisions@2021-11-04.yang
https://yangcatalog.org/yang-search/module_details/ietf-yang-library-revisions

Is this something we have to take into account?

Regards, B.

**Comment by JeanQuilbeufHuawei** [comment]
The effect of that one would be to add "revision-label" in the yang-library containers that already contain a revision. The module https://yangcatalog.org/yang-search/module_details/ietf-yang-library-revisions cannot achieve that because it does not augment our module:

in ietf-yang-library-revisions (one of) the path to augment is:
`/yanglib:yang-library/yanglib:module-set/yanglib:module`

whereas in our model the corresponding path to augment is
`/platform-manifest:plattform/platform-manifest:yang-library/yanglib:module-set/yanglib:module`

Maybe there is something wrong with our approach as we are using the yang-library where we should maybe use some other kind of inclusion (maybe mount?) so that if the platform supports yang-revisions then they appear in yang-library.

**Comment by JeanQuilbeufHuawei** [comment]
To do if not Mandatory
